#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#running pulseaudio
killall pulseaudio && pulseaudio &

#picom thing
pgrep -x picom > /dev/null || picom &

#this will lock the screen when suspending, since it doesnt using a suspeding manager thing
xss-lock --transfer-sleep-lock -- i3lock --nofork

#the network applet
pgrep -x nm-applet > /dev/null || nm-applet &

#the auto mounter for usbs
pgrep -x udiskie > /dev/null || udiskie -nt &


#the backgrounds
feh --bg-scale /home/alsetema/Pictures/Wallpapers/vladstudio.jpg /home/alsetema/Pictures/Wallpapers/sunset.jpg

#rule thing
bspc rule -r "*"

#set the mouse to focus windows without clicking
bspc config focus_follows_pointer true
#polybar
polybar main -r &
polybar left -r &

bspc monitor HDMI-A-1 -d 2 4 6 8 10 
bspc monitor HDMI-A-0 -d 1 3 5 7 9 
bspc config border_width         2
bspc config window_gap          15
bspc config top_padding         0
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
